###################################################################
# If you want o support this repository I accept donations        #
# even 1 TOK is always welcome :-)!                               #
# > ethereum address: 0x44F102616C8e19fF3FED10c0b05B3d23595211ce  #
# > tokugawa address: TqtycVQsthmEtMLGA8RtqHupZNPDH1Fnt9          #
###################################################################
#SECTION FOR BOT STYLE PARAMETERS
STYLE:
  FRAME:
    default_color:  0xff0000
    error_color:    0xcc0000

#SECTION FOR COIN SPECIFIC PARAMETERS
COIN:
    name:           Tokugawa
    acronym:        TOK
    decimals:       6
    explorer_url:   http://explorer.tokugawacoin.com/ext/getaddress/
    collateral:     2500

#SECTION FOR DISCORD PARAMETERS
DISCORD:
    api_key:          YOUR_DISCORD_API_KEY
